package com.revature.dao;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.SQLIntegrityConstraintViolationException;

import com.revature.beans.UserRole;
import com.revature.interfaces.DAO;
import com.revature.util.ConnectionUtil;

/**
 * DAO for user roles in Employee Reimbursement System
 * 
 * @author Bobby McGetrick
 *
 */
public class UserRoleDAO implements DAO<UserRole> {
	
	/************************************************************************************
	 * Constructors
	 ************************************************************************************/
	/**
	 * Create new UserRoleDAO
	 */
	public UserRoleDAO() {
		super();
		log.trace("Constructing new UserRoleDAO");
		log.trace("Called super constructor - Object");
		log.trace("New UserRoleDAO created");
	}

	/************************************************************************************
	 * Create
	 ************************************************************************************/
	/**
	 * Try to establish a connection to the ERS database using ConnectionUtil
	 * If connection is successful then build and send an Oracle SQL query to 
	 * insert a new UserRole to the ers_user_roles table
	 * 
	 * @param UserRole newUserRole
	 */
	@Override
	public int create(UserRole newUserRole) {
		log.trace("Method called to insert a new UserRole: " + newUserRole);
		log.trace("Attempting to get connection to  ERS database");
		
		try (Connection conn = ConnectionUtil.getConnection()) {
			log.trace("Connection established with database, creating prepared statement");
			PreparedStatement prepedStatement = conn.prepareStatement("INSERT INTO ers_user_roles "
					+ "(user_role)"
					+ " VALUES (?)",
					new String[] { "ers_user_role_id" });
			log.trace("Retrieve user name from the new user and inserting it into the SQL query");
			prepedStatement.setString(1, newUserRole.getRole());
			
			log.trace("Executing SQL query and retrieving the number of new rows inserted"
					+ "into ERS database's user role table");
			int numRowsInserted = 0;
			try {
				numRowsInserted = prepedStatement.executeUpdate();
			} catch (SQLIntegrityConstraintViolationException e) {
				log.warn("Failed to insert new user role - UserRole was not unique, printing stack trace");
			} catch (SQLException e) {
				log.warn("Failed to insert new user role - SQLException caught, printing stack trace");
				e.printStackTrace();
			}
			
			log.debug("SQL query inserted " + numRowsInserted + " rows into the ERS database's user table");
			
			log.trace("Retrieving the result set of the SQL query");
			ResultSet resultSet = prepedStatement.getGeneratedKeys();
			
			log.trace("Checking if result set has an entry");
			if (resultSet.next()) {
				log.trace("Setting the new user role's ID to the ID generated by the ERS database");
				newUserRole.setId(resultSet.getInt(1));
				log.trace("Returning the user ID generated by the ERS database");
				return resultSet.getInt(1);
			}
		} catch (SQLException e) {
			log.warn("Failed to insert new user role - SQLException caught, printing stack trace");
			e.printStackTrace();
		}
		log.trace("Returning 0");
		return 0;
	}

	/************************************************************************************
	 * Retrieve
	 ************************************************************************************/
	/**
	 * Try to establish a connection to the ERS database using ConnectionUtil If
	 * connection is successful then build and send an Oracle SQL query to retrieve
	 * a UserRole from the ers_use_roles table using the user role id
	 * 
	 * @param int id
	 *            
	 */
	@Override
	public UserRole get(int id) {
		log.trace("Method called to select a UserRole with id: " + id);
		log.trace("Attempting to get connection to ERS database");
		try (Connection conn = ConnectionUtil.getConnection()) {
			log.trace("Connection established with database, creating prepared statement");
			PreparedStatement prepedStatement = conn.prepareStatement("SELECT "
					+ "ers_user_role_id"
					+ ", user_role"
					+ " FROM ers_user_roles WHERE ers_user_role_id = ?");
			
			log.trace("Insertinting Id " + id + " into the SQL query");
			prepedStatement.setInt(1, id);
			
			log.trace("Executing SQL query and retrieving its resul set");
			ResultSet resultSet = prepedStatement.executeQuery();
		
			log.trace("Checking if result set has an entry");
			if (resultSet.next()) {
				log.trace("Creating a new UserRole with data from the result set");
				UserRole newUserRole = new UserRole(resultSet.getInt(
						"ers_user_role_id")
						, resultSet.getString("user_role"));
				log.trace("Returning UserRole wth id: " + id);
				return newUserRole;
			}
		} catch (SQLException e) {
			log.warn("Failed to retrieve user role with id " + id + " - SQLException caught, printing stack trace");
			e.printStackTrace();
		}
		log.trace("Returning null");
		return null;
	}
	
	@Override
	public UserRole get(UserRole arg0) {
		// TODO Auto-generated method stub
		return null;
	}

//	@Override
//	public UserRole get(String string) {
//		// TODO Auto-generated method stub
//		return null;
//	}

	/************************************************************************************
	 * Update
	 ************************************************************************************/
	/**
	 * Try to establish a connection to the ERS database using ConnectionUtil If
	 * connection is successful then build and send an Oracle SQL query to update a
	 * UserRole in the ers_user_roles table
	 * 
	 * @param UserRole userRoles
	 *            
	 */
	@Override
	public void update(UserRole userRole) {
		log.trace("Method called to update a UserRole: " + userRole);
		log.trace("Attempting to get connection to ERS database");
		try (Connection conn = ConnectionUtil.getConnection()) {
			log.trace("Connection established with database, creating prepared statement");
			PreparedStatement prepedStatement = conn.prepareStatement("UPDATE users "
					+ "SET user_role = " + userRole.getRole()
					+ " WHERE ers_user_id = " + userRole.getId());

			log.trace("Executing SQL query and retrieving the number of new rows updated"
					+ "in the ERS database's user roles table");
			int numRowsUpdated = prepedStatement.executeUpdate();
			log.debug("SQL query updated " + numRowsUpdated + " rows in the ERS database's user_roles table");
		} catch (SQLException e) {
			log.warn("Failed to update user role - SQLException caught, printing stack trace");
			e.printStackTrace();
		}
	}

	/************************************************************************************
	 * Delete
	 ************************************************************************************/
	/**
	 * Try to establish a connection to the ERS database using ConnectionUtil If
	 * connection is successful then build and send an Oracle SQL query to delete a
	 * UserRole to the ers_user_roles table
	 * 
	 * @param UserRole userRole
	 *            
	 */
	@Override
	public void delete(UserRole userRole) {
		log.trace("Method called to delete a UserRole: " + userRole);
		log.trace("Attempting to get connection to ERS database");
		try (Connection conn = ConnectionUtil.getConnection()) {
			log.trace("Connection established with database, creating prepared statement");
			PreparedStatement prepedStatement = conn.prepareStatement("DELETE FROM ers_user_roles"
					+ " WHERE ers_user_role_id = " + userRole.getId());

			log.trace("Executing SQL query and retrieving the number of new rows deleted"
					+ "into ERS database's user roles table");
			int numRowsDeleted = prepedStatement.executeUpdate();
			log.debug("SQL query inerted " + numRowsDeleted + " rows from the ERS database's user roles table");
		} catch (SQLException e) {
			log.warn("Failed to delete user role - SQLException caught, printing stack trace");
			e.printStackTrace();
		}
	}

}
